import type { Metadata, Viewport } from 'next';
import { SITE_URL } from '@/lib/siteUrl';
import Script from 'next/script';
import SplashScreen from '@/components/SplashScreen';
import { FxAnalytics } from '@/components/FxAnalytics';
import { PulseHost } from '@/components/pulse/PulseHost';
import '@/styles/globals.css';

const BASE_URL = SITE_URL;
// GA4 measurement ID — set NEXT_PUBLIC_GA_ID to enable, or use the
// current tag. Kept in one place so it's easy to change/disable.
const GA_ID = process.env.NEXT_PUBLIC_GA_ID ?? 'G-NXYRQ0MNE4';

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  title: {
    default:  'Busbar Calculator — Copper & Aluminum Busbar Cost Calculator',
    template: '%s | Busbar Calculator',
  },
  description:
    'Professional real-time copper and aluminum busbar cost calculator for electrical engineers. ' +
    'Live COMEX pricing, manual dimension inputs, 17 currencies, IEC standard cross-sections.',
  keywords: [
    'copper busbar', 'cost calculator', 'electrical panel', 'IEC 60317',
    'Cu-ETP', 'live copper price', 'COMEX', 'busbar weight',
    'شینه مسی', 'قیمت شینه مسی', 'محاسبه قیمت مس',
  ],
  authors:   [{ name: 'Busbar Calculator', url: BASE_URL }],
  creator:   'Busbar Calculator',
  publisher: 'Busbar Calculator',

  // Public launch: indexing ENABLED (launch checklist item #1 — done).
  // Private/app pages opt out individually (src/app/app/layout.tsx etc.).
  robots: {
    index:  true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },

  openGraph: {
    type:        'website',
    locale:      'en_US',
    url:          BASE_URL,
    siteName:    'Busbar Calculator',
    title:       'Busbar Calculator — Copper & Aluminum Busbar Cost Calculator',
    description: 'Live COMEX copper & aluminum pricing · 17 currencies · IEC standard cross-sections.',
    // Image is auto-generated by src/app/opengraph-image.tsx
  },

  twitter: {
    card:        'summary_large_image',
    title:       'Busbar Calculator — Copper & Aluminum Busbar Cost Calculator',
    description: 'Live COMEX copper & aluminum pricing · 17 currencies · IEC standard cross-sections.',
    // Image is auto-generated by src/app/opengraph-image.tsx

  },

  icons: {
    icon: [
      { url: '/icon', type: 'image/png', sizes: '512x512' }, // Mr Busbar
      { url: '/favicon.svg', type: 'image/svg+xml' },
    ],
    shortcut: '/icon',
    apple:   [{ url: '/apple-icon', sizes: '180x180', type: 'image/png' }],
    other:   [
      { rel: 'mask-icon', url: '/favicon.svg', color: '#cd7f32' },
    ],
  },

  // App Store / PWA
  appLinks: {},
  appleWebApp: {
    capable: true,
    title: 'Busbar Calc',
    statusBarStyle: 'black-translucent',
    startupImage: [],
  },

  manifest: '/manifest.json',

  // NOTE: no layout-level canonical — a canonical set here is inherited by
  // every page that doesn't define its own (signup, reset-password, /app/*,
  // /admin, /embed, /offline) and would wrongly point them all at the
  // homepage. Each indexable page declares its own canonical instead.
};

export const viewport: Viewport = {
  width:              'device-width',
  initialScale:        1,
  minimumScale:        1,
  viewportFit:        'cover',
  themeColor:         '#0b0d10',
  interactiveWidget:  'resizes-visual',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" style={{ background: '#0b0d10' }} suppressHydrationWarning>
      {/* Tell browsers and CDNs never to cache HTML pages */}
      <meta httpEquiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
      <meta httpEquiv="Pragma" content="no-cache" />
      <meta httpEquiv="Expires" content="0" />
      {/* Critical inline styles — dark background guaranteed even if CSS bundle fails to load */}
      <style dangerouslySetInnerHTML={{ __html:
        'html,body{background:#0b0d10!important;color:#f5f7fa;margin:0;padding:0;' +
        'font-family:Inter,ui-sans-serif,system-ui,sans-serif;-webkit-font-smoothing:antialiased}' +
        '*{box-sizing:border-box}'
      }} />
      <body style={{ background: '#0b0d10' }}>
        <SplashScreen />
        <FxAnalytics />
        <PulseHost />
        {GA_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
              strategy="afterInteractive"
            />
            <Script id="ga4-init" strategy="afterInteractive">{`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${GA_ID}');
            `}</Script>
          </>
        )}
        {children}
        {/* Global error capture — shows error on screen even if React can't mount */}
        <Script id="err-capture" strategy="beforeInteractive">{`
          window.__pp_errs = [];
          var __pp_errDiv = null;

          // Hard-reload with cache-bust after clearing all SW caches.
          // Called when stale chunks are detected so the browser fetches fresh HTML.
          function __pp_chunkReload() {
            try {
              var hasSW = 'serviceWorker' in navigator;
              var hasCaches = 'caches' in window;
              var dest = window.location.pathname + '?_pp=' + Date.now() + window.location.hash;
              var p = (hasSW && hasCaches)
                ? navigator.serviceWorker.getRegistrations()
                    .then(function(r) { return Promise.all(r.map(function(x) { return x.unregister(); })); })
                    .then(function() { return caches.keys(); })
                    .then(function(k) { return Promise.all(k.map(function(c) { return caches.delete(c); })); })
                : Promise.resolve();
              p.then(function() { window.location.href = dest; })
               .catch(function() { window.location.href = dest; });
            } catch(ex) {
              window.location.reload(true);
            }
          }

          function __pp_showErr(msg) {
            try {
              if (!__pp_errDiv) {
                __pp_errDiv = document.createElement('div');
                __pp_errDiv.setAttribute('style',
                  'position:fixed;top:0;left:0;right:0;z-index:99999;' +
                  'background:#1a0000;border-bottom:2px solid #ef4444;' +
                  'color:#fca5a5;padding:12px 16px;font:12px/1.5 monospace;' +
                  'white-space:pre-wrap;word-break:break-all;max-height:60vh;overflow:auto;');
                __pp_errDiv.innerHTML = '<b style="color:#ef4444">JS ERROR — Busbar Calculator (send this to dev):</b>\\n';
                document.body.appendChild(__pp_errDiv);
              }
              __pp_errDiv.innerHTML += msg + '\\n';
            } catch(ex) {}
          }

          // URL-based cycle detection (NOT sessionStorage) avoids "stuck flag"
          // bug where a previously failed recovery permanently blocks future
          // auto-fixes. ?_pp=<timestamp> is added on recovery; if it's already
          // there we don't loop.
          function __pp_alreadyTried() {
            return window.location.search.indexOf('_pp=') !== -1;
          }

          window.addEventListener('error', function(e) {
            var msg  = e.message  || '';
            var file = e.filename || '';
            // Stale chunk: script tag for an old content-hash fails to load (404)
            var isChunk =
              msg.indexOf('Loading chunk') !== -1 ||
              msg.indexOf('ChunkLoadError') !== -1 ||
              (file.indexOf('/_next/static/') !== -1 &&
               (msg === '' || msg === 'Script error.' || msg === 'Script error'));
            if (isChunk) {
              e.preventDefault();
              if (!__pp_alreadyTried()) { __pp_chunkReload(); return; }
              // Already tried recovery — show the error so the user knows
              __pp_showErr('Stale chunk after recovery — please hard-refresh');
              return;
            }
            var m = msg + '\\n  @ ' + file + ':' + e.lineno + ':' + e.colno;
            if (e.error && e.error.stack) m += '\\n' + e.error.stack;
            window.__pp_errs.push(m);
            __pp_showErr(m);
          });

          // Also catch <script> tag and <link> tag load failures (404). These
          // fire a non-bubbling 'error' on the element itself, not on window,
          // so the window 'error' handler above misses them unless we capture.
          window.addEventListener('error', function(e) {
            var t = e.target;
            if (!t || t === window) return;
            var src = t.src || t.href || '';
            if (src.indexOf('/_next/static/') !== -1) {
              if (!__pp_alreadyTried()) { __pp_chunkReload(); return; }
              __pp_showErr('Stale asset after recovery: ' + src);
            }
          }, true); // capture phase

          window.addEventListener('unhandledrejection', function(e) {
            var reason = e.reason;
            var rMsg = reason ? (reason.message || String(reason)) : '';
            // Stale chunk via dynamic import (Next.js lazy-loads chunks as promises)
            var isChunk =
              rMsg.indexOf('Loading chunk') !== -1 ||
              rMsg.indexOf('ChunkLoadError') !== -1;
            if (isChunk) {
              e.preventDefault();
              if (!__pp_alreadyTried()) { __pp_chunkReload(); return; }
              __pp_showErr('Stale chunk after recovery — please hard-refresh');
              return;
            }
            var m = 'Unhandled Promise: ' + rMsg;
            if (reason && reason.stack) m += '\\n' + reason.stack;
            window.__pp_errs.push(m);
            __pp_showErr(m);
          });
        `}</Script>
        {/* Register service worker; auto-fix stale cache if CSS bundle failed to load */}
        <Script id="sw-register" strategy="afterInteractive">{`
          (function() {
            function run() {
              // Check for cache-bust param BEFORE removing it — used below to
              // detect that we already attempted a redirect this navigation.
              var alreadyRedirected = window.location.search.indexOf('_pp=') !== -1;

              // Clean up cache-bust param from URL bar (cosmetic)
              if (alreadyRedirected) {
                try { history.replaceState(null, '', window.location.pathname + window.location.hash); } catch(e) {}
              }

              var cssLoaded = !!(getComputedStyle(document.documentElement)
                .getPropertyValue('--color-copper-500') || '').trim();

              // CSS missing AND this is not already a post-redirect load:
              // clear all SW registrations + caches, then hard-navigate with a
              // cache-busting query param so the browser fetches fresh HTML.
              // Using URL-state (not sessionStorage) avoids the "stuck flag" bug
              // where a previously failed redirect blocks all future auto-fixes.
              if (!cssLoaded && !alreadyRedirected) {
                var hasSW = 'serviceWorker' in navigator;
                var hasCaches = 'caches' in window;
                var p = (hasSW && hasCaches)
                  ? navigator.serviceWorker.getRegistrations()
                      .then(function(r) { return Promise.all(r.map(function(x) { return x.unregister(); })); })
                      .then(function() { return caches.keys(); })
                      .then(function(k) { return Promise.all(k.map(function(c) { return caches.delete(c); })); })
                  : Promise.resolve();
                p.then(function() {
                  window.location.href = window.location.pathname + '?_pp=' + Date.now() + window.location.hash;
                }).catch(function() {
                  window.location.href = window.location.pathname + '?_pp=' + Date.now() + window.location.hash;
                });
                return;
              }

              // CSS is loaded (or we already redirected once) — register SW normally.
              // Also clear legacy stuck-flags from older versions.
              try {
                sessionStorage.removeItem('pp_css_fix');
                sessionStorage.removeItem('pp_chunk_retry');
              } catch(e) {}
              if ('serviceWorker' in navigator) {
                navigator.serviceWorker.register('/sw.js').catch(function(){});
              }
            }
            if (document.readyState === 'complete') {
              run();
            } else {
              window.addEventListener('load', run);
            }
          })();
        `}</Script>
      </body>
    </html>
  );
}
